server:
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: true
  application:
    name: wind-farm
  datasource:
    url: jdbc:postgresql://localhost:5432/wind_farm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  kafka:
    bootstrap-servers: pkc-56d1g.eastus.azure.confluent.cloud:9092
    properties:
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      security.protocol: SASL_SSL
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="34TMAWD7NIMMRSHW" password="ADkX1K+OmL+vXgP5bFxyqGHWqUdWT5u8Ce7FrSfiHwqKc1cbpi8lvkJuFFkrLSWW";
#
#logging:
#  level:
#    org:
#      springframework:
#        kafka: DEBUG
#      apache:
#        kafka: DEBUG